### ISSUE TITLE
How to get current position of the turtle?

### ISSUE THREAD

**Issue by asif-r-porosh** [leonceaklin/real-turtle#1]
Thanks a lot for the lib. I was wondering if there is any implemented method to get current coordinate of the turtle. I dont see any in the doc. Thanks in advance.

**Comment by leonceaklin** [comment]
Hey
I'm glad you like it.
That information can be accessed via the turtle's `state` property. Since the turtle 'parses' your commands in advance, you should read it inside an `.eval()` command.

Here's an example:
```js
turtle.setPosition(0,0)
turtle.right(90)
turtle.forward(100)
turtle.eval(() => {
   //By putting this inside an eval command, it doesn't get executed until the turtle has finished the preceding tasks
   console.log(turtle.state.position)
})
```
Output in your console:
```js
{x: 100, y: 0}
```

Hope this helps :)
Best regards
Léonce

**Comment by asif-r-porosh** [comment]
Thank you. :)

**Comment by asif-r-porosh** [comment]
Hi, Is there any mechanism to run commands sequentially? By this what I mean is, I want to run the subsequent command only after the first command finishes execution. For example: 
```
turtle.move(200)
console.log("Done")
```
I want "Done" to be printed after the turtle reaches its destination on screen. In my scenerio I will run a lot of commands one after another. And i think next command can be triggered in eval block. Is this the way?

**Comment by leonceaklin** [comment]
The problem with this is that JavaScript won't "wait" until the turtle has finished the task because the turtle's methods are asynchronous. I've now implemented a new `async`-mode which allows you to achieve what you're aiming for. You can see it in action in [this REPL](https://replit.com/@leonceaklin/RealTurtleAsyncTemplate#index.html). A RealTurtle instance which uses async mode can be created like this:
```js
var turtle = new RealTurtle([your canvas], {async: true})

//or in the browser
var turtle = new RealTurtle.default([your canvas], {async: true})
```

Note that you have to use `await` to call your functions and that everything has to be packed inside an asynchronous function since you can't use `await` in the top level:

```js
async function run(){
     //Your turtle commands go here
     await turtle.move(200)
     console.log("Done")
}
run()
```

**Comment by asif-r-porosh** [comment]
Thanks a lot for your reply. I think this will solve my problem.

**Comment by asif-r-porosh** [comment]
Hello again, 

`turn(a)` always turns relative to its current angle. Whats the preferred way to reset turtle to face north without knowing current angle?
I found if I call `turn(a)` without  parameter like this- `t.turn()` then the turtle faces north. Is it ok?

Thanks a lot for replying all my queries.

**Comment by asif-r-porosh** [comment]
Writing again as I am not sure if you have received my last query. Appreciate your kind help. Pls excuse me.

**Comment by leonceaklin** [comment]
Sorry for letting you wait for such a long time…
It wasn't intended to work that way but now I implemented that behaviour officially that it faces north when you use `t.turn()` without any arguments.
